server:
  servlet:
    context-path: /api
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://dummydb.cjdhgdrnyut6.us-east-1.rds.amazonaws.com:5432/dummydbprof
    username: devforfun
    password: devforfun1699
    pool-size: 30
